# Generated by Django 5.0.4 on 2024-04-27 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lesson',
            options={'ordering': ['-_id']},
        ),
        migrations.AddField(
            model_name='lesson',
            name='long_description',
            field=models.TextField(null=True),
        ),
    ]
