# Generated by Django 5.0.4 on 2024-04-27 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taapp', '0002_alter_lesson_options_lesson_long_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='tag',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
