# Generated by Django 5.0.4 on 2024-04-27 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taapp', '0003_message_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='handled',
            field=models.BooleanField(default=False),
        ),
    ]
