# Generated by Django 5.0.4 on 2024-04-27 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taapp', '0004_lesson_handled'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='handled_bert',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lesson',
            name='handled_bert_emo',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lesson',
            name='handled_saiga',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lesson',
            name='start_time',
            field=models.DateTimeField(null=True),
        ),
    ]
