# Generated by Django 5.0.4 on 2024-04-27 23:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taapp', '0006_rename_tag_message_tag_bert1_message_tag_bert2'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lesson',
            options={'ordering': ['-handled_saiga', '-_id']},
        ),
    ]
