# Generated by Django 5.0.4 on 2024-04-28 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taapp', '0007_alter_lesson_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='handled_saiga2',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lesson',
            name='long_description2',
            field=models.TextField(null=True),
        ),
    ]
